Update sub.yml

diff --git a/.github/workflows/sub.yml b/.github/workflows/sub.yml
--- a/.github/workflows/sub.yml
+++ b/.github/workflows/sub.yml
@@ -60,8 +60,8 @@ jobs:
           {
             echo 'urls<<EOF'
             curl -sL ${{ github.event.inputs.subject_url }} | jq -r .assets[].browser_download_url | grep -E '\.apks?$' | grep -v x86
-            echo 'EOF'
-          } >> GITHUB_OUTPUT || { echo "result=failure" >> $GITHUB_OUTPUT; exit 0; }
+            echo EOF
+          } >> $GITHUB_OUTPUT || { echo "result=failure" >> $GITHUB_OUTPUT; exit 0; }
           
       - name: vt scan urls
         id: scan-urls
