Update sub.yml

diff --git a/.github/workflows/sub.yml b/.github/workflows/sub.yml
--- a/.github/workflows/sub.yml
+++ b/.github/workflows/sub.yml
@@ -55,20 +55,17 @@ jobs:
       - name: extract apk(s) urls
         id: find-apk-urls
         run: |
-          urls=$(curl -sL ${{ github.event.inputs.subject_url }} | jq -r .assets[].browser_download_url | grep -E '\.apks?$' | grep -v x86) || { echo "result=failure" >> $GITHUB_OUTPUT; exit 0; }
-          printf "%s\n" $urls
-          # echo "urls=$urls" >> $GITHUB_OUTPUT
-          echo "urls<<EOF" >> $GITHUB_OUTPUT
-          echo "urls=$urls" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-  
+          curl -sL ${{ github.event.inputs.subject_url }} | jq -r .assets[].browser_download_url | grep -E '\.apks?$' | grep -v x86 > ~/urls.txt || { echo "result=failure" >> $GITHUB_OUTPUT; exit 0; }
+          cat ~/urls.txt
+          
       - name: vt scan urls
         id: scan-urls
         if: steps.find-apk-urls.outputs.result != 'failure'
         run: |
-          printf "%s\n" ${{ steps.find-apk-urls.outputs.urls }}
+          cat ~/urls.txt
+          # printf "%s\n" ${{ steps.find-apk-urls.outputs.urls }}
           #vt scan url - <<< ${{ steps.find-apk-urls.outputs.urls }} | cut -f 2 -d ' ' | vt analysis -
-          printf "%s\n" ${{ steps.find-apk-urls.outputs.urls }} | vt scan url - | cut -f 2 -d ' ' | vt analysis -
+          cat ~/urls.txt | vt scan url - | cut -f 2 -d ' ' | vt analysis -
           
       - name: vt scan files
         if: steps.find-apk-urls.outputs.result != 'failure'
