Update vt-sh.yml

diff --git a/.github/workflows/vt-sh.yml b/.github/workflows/vt-sh.yml
--- a/.github/workflows/vt-sh.yml
+++ b/.github/workflows/vt-sh.yml
@@ -1,5 +1,7 @@
 name: Analysis
 on:
+  repository_dispatch:
+    types: [analysis]
   workflow_dispatch:
     inputs:
       subject_url:
@@ -12,14 +14,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Print Subject URL
-        run: echo "Received subject_url:" "${{ github.event.inputs.subject_url }}"
+        run: |
+          SUBJECT_URLs="${{ github.event.client_payload.subject_url || github.event.inputs.subject_url }}"
+          echo "Received subject_url:" $URLs"
 
       - name: Cache vt
         id: cache-vt
         uses: actions/cache@v4
         with:
           path: ~/vt
-          key: vt-${{ runner.os }}-vt-1.1.1
+          key: vt-${{ runner.os }}-vt-1.3.0
           restore-keys: vt-${{ runner.os }}-
     
       - name: Cache jq
@@ -32,8 +36,8 @@ jobs:
       - name: Download and install vt
         if: steps.cache-vt.outputs.cache-hit != 'true'
         run: |
-          curl -L -o vt.zip https://github.com/VirusTotal/vt-cli/releases/download/1.1.1/Linux64.zip
-          echo "82107394601c5669771be1f11d2ceb2f13f4117d72a3e6346b4ed13a6f10878c vt.zip" | sha256sum -c
+          curl -L -o vt.zip https://github.com/VirusTotal/vt-cli/releases/download/1.3.0/Linux64.zip
+          echo "2d3d67c84e9cf43c50b6655af73f8df010e1185370059a0c9c72ff39dd33def4 vt.zip" | sha256sum -c
           unzip vt.zip
           chmod +x vt
           mv vt ~/vt
@@ -55,17 +59,39 @@ jobs:
       - name: extract apk(s) urls
         id: find-apk-urls
         run: |
-          curl -sL ${{ github.event.inputs.subject_url }} | jq -r .assets[].browser_download_url | grep -E '\.apks?$' | grep -v x86 > ~/urls.txt || echo "result=failure" >> $GITHUB_OUTPUT
-          cat ~/urls.txt || exit 0
+          # curl -sL $SUBJECT_URLs | jq -r .assets[].browser_download_url | grep -E '\.apks?$' | grep -v x86 > ~/urls.txt || echo "result=failure" >> $GITHUB_OUTPUT
+          # cat ~/urls.txt || exit 0
+
+          DL_URLS=$(curl -sL $SUBJECT_URLs | jq -r '.assets[].browser_download_url')
+
+          APKs=$(echo "$DL_URLS" | grep -iE '(arm64|v8a?|armv8a?).+\.apk$')
+
+          if [ -z "$APKs" ]; then
+              APKs=$(echo "$DL_URLS" | grep -iE '\.apk$')
+          fi
+
+          if [ -z "$APKs" ]; then
+              APKs=$(echo "$DL_URLS" | grep -iE '\.apks$')
+          fi
+
+          if [ -z "$APKs" ]; then
+              echo "No matching assets found."
+              echo "result=failure" >> $GITHUB_OUTPUT
+          fi
+
+          echo "$APKs"
           
       - name: vt scan urls
         id: scan-urls
         if: steps.find-apk-urls.outputs.result != 'failure'
         run: |
-          cat ~/urls.txt
-          # cat ~/urls.txt | vt scan url - | cut -f 2 -d ' ' | vt analysis -
-          # while IFS= read -r url; do vt scan url "$url" | cut -f 2 -d ' ' | vt analysis -; done < ~/urls.txt
-          while IFS= read -r url; do vt scan url "$url" ; done < ~/urls.txt
+          # cat ~/urls.txt
+          # # cat ~/urls.txt | vt scan url - | cut -f 2 -d ' ' | vt analysis -
+          # # while IFS= read -r url; do vt scan url "$url" | cut -f 2 -d ' ' | vt analysis -; done < ~/urls.txt
+          # while IFS= read -r url; do vt scan url "$url" ; done < ~/urls.txt
+
+          wget2 "$APKs"
+          find . -maxdepth 1 \( -name '*.apk' -o  -name '*.apks' \) -exec vt scan file {} \+
           
       # - name: vt scan files
       #   if: steps.find-apk-urls.outputs.result != 'failure'
